---
# tasks file for frontend
- name: Start a container with the frontend and connect to network
  #community.docker.docker_container:
  docker_container:
    ports:
      - "80:80"
    volumes:
      - /home/aurelien/student-list/website:/var/www/html 
    env:
      USERNAME: "toto"
      PASSWORD: "python"
    name:  ihm-projet-a
    image: php:apache
    networks:
      - name: "{{ networkname }}"